baseURL       = "http://example.org/"
languageCode  = "en-us"
title         = "Vesna Burcul | Psihoterapeut"
theme         = "roxo-hugo-clone"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Naslovna"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "O meni"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Kontakt"
    url     = "contact"
    weight  = 4

# Site Params
[params]
  logo = "images/logo.png"
  logo_footer = "images/logo-footer.png"
  favicon_icon = "images/favicon.ico"
  favicon_shortcut_icon = "images/favicon.png"
  custom_stylesheets = []   # [ "scss/my_1.scss", "scss/my_2.scss" ]
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Reci-Da psihoterapeut Vesna Burcul"
  author = "Marko Burcul"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  fabform  = "https://fabform.io/f/7LoH_if"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "Ime"
    placeholder_last_name         = "Prezime"
    placeholder_email             = "Email"
    placeholder_service_type      = "Vrsta usluge"
    placeholder_message           = "Poruka"
    send_message                  = "Pošalji poruku"

    [[params.contactForm.projectType]]
      value = "Savjetovanje"
      title  = "Savjetovanje"
    [[params.contactForm.projectType]]
      value = "Individualna psihoterapija"
      title  = "Individualna psihoterapija"
    [[params.contactForm.projectType]]
      value = "Partnerska psihoterapija"
      title  = "Partnerska psihoterapija"
    [[params.contactForm.projectType]]
      value = "Obiteljska psihoterapija"
      title  = "Obiteljska psihoterapija"
    [[params.contactForm.projectType]]
      value = "Supervizija"
      title  = "Supervizija"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Kontakt"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.jpg"
    heading               = "Psihoterapija"
    primary_button        = "O psihoterapiji"
    primary_button_url    = "blog"
    secondary_button      = "Kontaktirajte me"
    secondary_button_url  = "contact"

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "Surađujmo zajedno"
    primary_button      = "Kontakt"
    primary_button_url  = "contact"

  [params.footer]
    params.footer.qr_print = false
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Kontakt"
      address = "Ljudevita Posavskog 10, 23000 Zadar, Hrvatska"
      phone   = "098 9666114"
      email   = "burculvesna@gmail.com"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Mapa stranice"
        [[params.footer.sitemap.link]]
          name = "O meni"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Kontakt"
          url  = "contact"
      # Footer Service
      [params.footer.service]
        title       = "Rezervacije termina i upiti"
        description = "Upit ili rezervaciju termina možete poslati putem kontakt obrasca. Primit ćete potvrdu o poslanom upitu putem emaila, a odgovorit ćemo Vam u najkraćem mogućem roku."
      [params.footer.back_to_top]
        description = "Natrag na vrh"
